# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 13:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import formlab.core.resources


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('slug', models.SlugField(max_length=150, verbose_name='Slug')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('xls_file', models.FileField(max_length=255, upload_to=formlab.core.resources.FileUploadPath('xlsfiles'), verbose_name='XLS File')),
                ('xlsform_file', models.FileField(blank=True, editable=False, max_length=255, null=True, upload_to=formlab.core.resources.FileUploadPath('xlsforms'), verbose_name='XLSForm File')),
                ('group', models.ManyToManyField(blank=True, null=True, to='auth.Group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
            },
        ),
    ]
