# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20160516_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='group',
            new_name='groups',
        ),
    ]
